displayName=Gold Withdraw Warning
author=S
description=Warns players when withdrawing gold above a set threshold.
tags=gold,withdraw,warning,ironman,iron,gp,coins,pickup,drops,pvm,loot
plugins=com.goldwithdrawamount.GoldWithdrawAmountPlugin
build=standard
